"""Phase A: can a block-aware surrogate predict that the six known gauge
endpoints are harmful, when the ordinary layer objective says they are good?

Each endpoint is regenerated by re-running its layer's discrete Givens search
from the ORIGINAL post-ADMM state (the search is deterministic), scored, and then
rolled back, so all six are measured relative to the same NanoQuant state and
never compound.  No Step 3 anywhere.
"""
import argparse
import json
import os
import time

import torch

from nanoquant.modules.hub import NanoQuantConfigDataclass  # noqa: F401  import-order guard

import instrument as I

from . import block_surrogate as BS
from . import core as C
from . import curvature as CV
from . import givens as GV
from . import harness as H
from . import layer_oracle as LO
from . import state as S

LAYERS = [n for n in H.NAMES if n != "mlp.down_proj"]
LAMBDAS = [0.25, 0.5, 1.0, 2.0, 4.0]
LAM_WIDE = [10.0 ** k for k in range(-12, 13, 2)]
OUT = "/home/work/exp/results/nanoquant/gauge/curvature"


@torch.no_grad()
def deployed_W(module):
    return I.effective_weight(module).double()


def main(a):
    os.makedirs(OUT, exist_ok=True)
    torch.manual_seed(a.seed)
    st = H.load_post_admm(seed=a.seed)
    blk, kwargs = st["blk"], st["kwargs"]
    sub = H.nq_sub(blk)
    cal_in, cal_out = st["cal_in"].to("cuda"), st["cal_out"].to("cuda")
    C.GUARD.assert_not_heldout(cal_in, cal_out, where="surrogate_diagnostic")

    def block_err():
        return H.func_loss_over(blk, cal_in, cal_out, kwargs)

    E0 = block_err()
    rec = {"seed": a.seed, "E_block_ADMM": E0, "nb": a.nb,
           "lambdas": LAMBDAS, "lambdas_wide": LAM_WIDE, "endpoints": [], "checks": {}}
    print(f"[diag] block error at the original NanoQuant state = {E0:.8f}", flush=True)

    # curvature at the ORIGINAL state, once
    curv = CV.collect(st, layers=LAYERS, n_seq=a.n_seq, h_out_samples=a.h_out_samples)
    rec["checks"]["h_out_stride"] = curv[LAYERS[0]].h_out_stride
    rec["checks"]["h_out_samples"] = curv[LAYERS[0]].n_hout
    rec["checks"]["n_tokens"] = curv[LAYERS[0]].n_tokens
    psd = []
    for n in LAYERS:
        psd.append(BS.test_psd(curv[n].H_in, f"{n}.H_in"))
        psd.append(BS.test_psd(curv[n].H_out, f"{n}.H_out"))
    rec["checks"]["psd"] = psd
    print("[diag] PSD/symmetry checks: %d/%d pass" % (sum(p["pass"] for p in psd), len(psd)),
          flush=True)

    oracles = LO.build_all(st, n_seq=a.n_seq)
    bases = {n: C.LayerBase(n, sub[n]).to("cuda") for n in LAYERS}

    for name in LAYERS:
        t0 = time.time()
        base, cu = bases[name], curv[name].to("cuda")
        o = oracles[name].to("cuda")   # Oracle is built on CPU; move before scoring
        W_cur = deployed_W(sub[name])
        W_fp = st["W_refs"][name].to("cuda").double()
        recon_before = o.error(W_cur.float())

        # --- H_in orientation unit test, once, on this layer's real activations
        if name not in rec["checks"]:
            pass

        # --- regenerate the endpoint: same search, same settings, from ADMM ---
        ps = GV.PlaneSearcher(o, base)
        nb = min(a.nb, base.rank // 32)
        acc = 0
        for gi in range(nb):
            gp = list(range(gi * 32, gi * 32 + 32))
            for x in range(32):
                for y in range(x + 1, 32):
                    r = ps.sweep(gp[x], gp[y])
                    if GV._accept_ok(r, o, max(recon_before, 1e-12), a):
                        ps.apply(r["i"], r["j"], r["theta"])
                        acc += 1
        R = ps.R.clone()

        # gauge invariance of the CONTINUOUS product
        with torch.no_grad(), C.no_tf32():
            P0 = base.U0.double() @ base.V0.double()
            PR = (base.U0.double() @ R) @ (R.T @ base.V0.double())
            inv = float((PR - P0).norm() / max(float(P0.norm()), 1e-30))

        H.apply_gauge_signs_only(sub[name], base, [R.float()])   # fixed ADMM scales
        W_cand = deployed_W(sub[name])
        E_after = block_err()
        recon_after = o.error(W_cand.float())
        dW = W_cand - W_cur

        sU = float((C.pos_sign(base.U0.double() @ R) != C.pos_sign(base.U0.double())).sum())
        sV = float((C.pos_sign(R.T @ base.V0.double()) != C.pos_sign(base.V0.double())).sum())

        H_in_sum = cu.H_in * cu.n_tokens
        s0 = BS.s0_layer_recon_delta(W_cur, W_cand, W_fp, H_in_sum)
        s1 = BS.s1_input_quadratic(dW, cu.H_in)
        s2 = BS.s2_kfac_quadratic(dW, cu.H_in, cu.H_out, cu.n_tokens)
        s3 = BS.s3_block_linear(dW, cu.G_W)
        true_d = E_after - E0

        ent = {"layer": name, "accepted_moves": acc, "rank_blocks": nb,
               "recon_before": recon_before, "recon_after": recon_after,
               "recon_delta_pct": 100 * (recon_after - recon_before) / abs(recon_before),
               "E_block_before": E0, "E_block_after": E_after,
               "true_delta": true_d, "true_delta_pct": 100 * true_d / E0,
               "S0": s0, "S1": s1, "S2": s2, "S3": s3,
               "S4": {str(l): s3 + l * s2 for l in LAMBDAS},
               "S4_wide": {f"{l:.0e}": s3 + l * s2 for l in LAM_WIDE},
               "sign_changes_U": sU, "sign_changes_V": sV, "hamming": sU + sV,
               "continuous_product_rel_change": inv,
               "correct_S0": bool((s0 > 0) == (true_d > 0)),
               "correct_S1": bool((s1 > 0) == (true_d > 0)),
               "correct_S2": bool((s2 > 0) == (true_d > 0)),
               "correct_S3": bool((s3 > 0) == (true_d > 0)),
               "seconds": time.time() - t0}
        rec["endpoints"].append(ent)
        print(f"[diag] {name:<18} recon {ent['recon_delta_pct']:+.3f}%  true block "
              f"{ent['true_delta_pct']:+.4f}%  S0 {s0:+.3e} S1 {s1:+.3e} "
              f"S2 {s2:+.3e} S3 {s3:+.3e}  inv {inv:.1e}  ({time.time()-t0:.0f}s)",
              flush=True)

        # persist first, so a later failure cannot lose completed rows
        S.atomic_json(rec, f"{OUT}/endpoint_diagnostic.json")

        # Roll back to the original NanoQuant state before the next layer.  No
        # check_identity here: that flag compares the freshly materialised
        # tensors against the module's *current* contents, which still hold the
        # gauged endpoint at this point, so it would always fire.  Restoration is
        # verified against the block error instead.
        H.materialize_gauge(sub[name], base, C.identity_Rs(base.rank, 32, "cuda"))
        back = block_err()
        assert abs(back - E0) < 1e-9, \
            f"{name}: rollback left block error at {back:.10f}, expected {E0:.10f}"
        del ps
        torch.cuda.empty_cache()

    # --- accuracy summary ---
    eps = rec["endpoints"]
    n = len(eps)
    summ = {k: sum(e[f"correct_{k}"] for e in eps) for k in ["S0", "S1", "S2", "S3"]}
    summ["S4"] = {str(l): sum(((e["S4"][str(l)] > 0) == (e["true_delta"] > 0)) for e in eps)
                  for l in LAMBDAS}
    summ["S4_wide"] = {k: sum(((e["S4_wide"][k] > 0) == (e["true_delta"] > 0)) for e in eps)
                       for k in eps[0]["S4_wide"]}
    rec["accuracy_out_of"] = n
    rec["accuracy"] = summ
    S.atomic_json(rec, f"{OUT}/endpoint_diagnostic.json")
    print("\n[diag] direction accuracy out of %d:" % n)
    for k in ["S0", "S1", "S2", "S3"]:
        print(f"   {k}: {summ[k]}/{n}")
    print("   S4:", {k: f"{v}/{n}" for k, v in summ["S4"].items()})
    print("   S4 wide lambda:", {k: f"{v}/{n}" for k, v in summ["S4_wide"].items()})
    return rec


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--nb", type=int, default=8)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n_seq", type=int, default=0)
    ap.add_argument("--h_out_samples", type=int, default=32768)
    ap.add_argument("--tol", type=float, default=1e-7)
    ap.add_argument("--noise_k", type=float, default=10.0)
    a = ap.parse_args()
    a.n_seq = a.n_seq or None
    main(a)
